# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Marie Zufferey
tagline:          'Some useful stuff'
description:      'Miscellanous programming & co. things.'
url:              http://mzufferey.github.io
baseurl:          /

author:
  name:           'Marie Zufferey'
  url:            https://mzufferey.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://mzufferey.github.io
